ft(assign) assign drivers buses
atlp-rwanda/phatom-be-techode pull request #21
Opened 2022-04-14 09:42 UTC by wakaflorien

### What this PR does 

> This pr gives operator the ability to delete create update and read the buss

- [x] The operator should be able to view a paginated list of driver to bus assignments.
- [x] The operator should be able to assign a driver to a bus..
- [x] The driver should receive a bus assignment and unassignment email & in-app notifications..
- [x] Appropriate error messages are displayed on unsuccessful attempts.

## Trello card Id

#TP-12

## How you can manually test it

**Clone the repo**
then checkout to **ft-crud-operations-for-buses-TP-12** branch

**Installation of dependencies.**
```
npm i

```

**To update your DB run this**

```
npm run migrate
npm run seedAll

```

**Start Docker**

```
docker-compose build
docker-compose up
```

### OR

**Dev server**

```
npm run dev
```

**Eslint**
```
npm run lint
```

**Development links for docker**
[Frontend](http://localhost:8080/) 
[Backend](http://localhost:5000/)

**Development links for dev server (npm run dev)**
[Backend](http://localhost:5000/)
[Api doc](http://localhost:5000/api/v1/doc)

## Trello
https://trello.com/c/cyFXrIZt

2022-04-20 18:32 UTC, Jkadhuwa requested changes, later dismissed
hey @wakaflorien nice work so far. 

- Nice work on the pagination
- act on the feedback below
- solve the code climate issues

2022-04-20 18:32 UTC, Jkadhuwa commented on controllers/userController.js
> +		const { error } = validateUsersOnCreate({firstname:firstname, lastname:lastname, username:username, email:email, telephone:telephone, userType:userType})
Use the validations as middleware on router section

2022-04-20 18:32 UTC, Jkadhuwa commented on controllers/userController.js
> +		const userExist = await users.findAll({
Just use findByPk or findOne, they return the first entry when found rather than findAll

2022-04-20 18:32 UTC, Jkadhuwa commented on controllers/userController.js
> +			telephone: req.body.telephone,
make use of object destructuring

2022-04-20 18:32 UTC, Jkadhuwa commented on controllers/userController.js
> +        const userExist = await users.findAll({
Also here use findByPk

2022-04-20 18:32 UTC, Jkadhuwa commented on controllers/userController.js
> +    const userExist = await users.findAll({
same here

2022-04-20 18:32 UTC, Jkadhuwa commented on controllers/userController.js
> +        const userExist = await users.findAll({
same here

2022-04-20 18:32 UTC, Jkadhuwa commented on test/user.test.js
> +		// 		where: { isDeleted : false }
- You can remove commented code.
- use es6 imports in tests

2022-04-20 18:32 UTC, Jkadhuwa commented on test/user.test.js
>  		expect(response).to.have.status(201);
Add more assertions to your tests

2022-04-22 08:40 UTC, wakaflorien commented on test/user.test.js
>  		expect(response).to.have.status(201);
done

2022-04-22 08:40 UTC, wakaflorien commented on controllers/userController.js
> +        const userExist = await users.findAll({
done

2022-04-22 08:40 UTC, wakaflorien commented on controllers/userController.js
> +    const userExist = await users.findAll({
done

2022-04-22 08:40 UTC, wakaflorien commented on controllers/userController.js
> +        const userExist = await users.findAll({
done

2022-04-22 08:41 UTC, wakaflorien commented on controllers/userController.js
> +        const userExist = await users.findAll({
done

2022-04-25 07:05 UTC, chanceDira approved these changes
Good job @wakaflorien

2022-04-25 07:30 UTC, jeandamascyifuzo approved these changes

2022-04-25 09:10 UTC, sezeranoJchrisostome approved these changes
Well done @wakaflorien

2022-04-25 10:49 UTC, renepromesse requested changes
Nice work @wakaflorien , please attend the following feedback as soon  as you can

2022-04-25 10:49 UTC, renepromesse commented on test/bus.test.js
>  		};
create a dummy data file and add in this user object,
everywhere you're using this object should be called/imported from the dummy data file

2022-04-25 10:49 UTC, renepromesse commented on test/resetPassword.test.js
>  		};
don't declare an new user object call the one you added in the dummy data

2022-04-25 10:49 UTC, renepromesse commented on test/resetPassword.test.js
>  		};
add this email and password below in the dummy data

2022-04-25 10:49 UTC, renepromesse commented on test/resetPassword.test.js
> +		const user = await users.findOne({ where: { email: 'daaaqk@example.com' } });
call this email from the dummy file

2022-04-25 10:49 UTC, renepromesse commented on test/resetPassword.test.js
> +		const user = await users.findOne({ where: { email: 'daaaqk@example.com' } });
👆️this email too

2022-04-25 10:49 UTC, renepromesse commented on test/resetPassword.test.js
> +		const user = await users.findOne({ where: { email: 'daaaqk@example.com' } });
same here

2022-04-25 10:49 UTC, renepromesse commented on test/role.test.js
>  		};
refactor this user object too

2022-04-25 10:49 UTC, renepromesse commented on test/role.test.js
>          };
same here too

2022-04-25 10:49 UTC, renepromesse commented on test/route.test.js
> +		// });
remove this comments

2022-04-25 10:49 UTC, renepromesse commented on test/user.test.js
>  		};
refactor this user object as well

2022-04-25 10:49 UTC, renepromesse commented on test/user.test.js
> +		};
add this driver object in the dummy data fiile

2022-04-25 10:49 UTC, renepromesse commented on test/user.test.js
> +		};
refactor this driver too

2022-04-25 10:49 UTC, renepromesse commented on test/user.test.js
>  		};
refactor this user too

2022-04-25 10:49 UTC, renepromesse commented on test/user.test.js
> +		// response.body.data.role.should.be.a('array');
remove this commented lines

2022-04-25 10:49 UTC, renepromesse commented on test/user.test.js
> +		// response.body.data.users.should.be.a('array');
review all your codes and remove all commented codes

2022-04-25 14:30 UTC, wakaflorien commented on test/user.test.js
>  		};
done

2022-04-25 14:31 UTC, wakaflorien commented on test/user.test.js
>  		};
done

2022-04-25 14:31 UTC, wakaflorien commented on test/route.test.js
> +		// });
done @renepromesse

2022-04-25 16:40 UTC, renepromesse approved these changes
Great work

2022-04-25 16:51 UTC, merged