#TP-38 ft:update-profile
atlp-rwanda/phatom-be-techode pull request #22
Opened 2022-04-15 14:51 UTC by jeandamascyifuzo

**What this PR does**
This pr gives the operator or driver the ability to update their profile

- [x] The operator should be able to update information about his/her own profile.
- [x] The driver should be able to update information about his/her own profile.
- [ ] The operator and driver profile should be able accessible publicly.
- [x] Appropriate error messages are displayed on unsuccessful attempts.

**Trello card link**
[update profile](https://trello.com/c/UJYesI3N/38-update-profile)

**How you can manually test it**
Clone the repo
then checkout to ft-update-profile-TP-38 branch

**Installation of dependencies.**
npm i

**To update your DB run this**

npm run migrate
npm run seedAll

2022-04-20 14:01 UTC, Jkadhuwa requested changes
Nice work @jeandamascyifuzo, act on the feedback below.

2022-04-20 14:01 UTC, Jkadhuwa commented on controllers/profileContoller.js
> +		if (!req.body.profileImage) throw new Error('profile image link required');
Why redefine the wheel, when we already have joi installed.

2022-04-20 14:01 UTC, Jkadhuwa commented on controllers/profileContoller.js
> +		console.log(err)
- No need of this console (Remove all unused consoles)
- Use the custom response handler sendError() {consistency}

2022-04-20 14:01 UTC, Jkadhuwa commented on controllers/userController.js
> +			if(!req.body.username && !req.body.password &&  !req.body.fullname && !req.body.email && !req.body.profileImage) throw new Error('Body is required');
Also here use joi to validate your body, in the routes section before hitting the controller.

2022-04-20 14:01 UTC, Jkadhuwa commented on test/user.test.js
> +		expect(response).to.have.status(201);
Add more assertions to your tests, you can check the response {message, etc}

2022-04-20 14:01 UTC, Jkadhuwa commented on test/user.test.js
> +    //         startLocation: "Rwamagan",
Remove all commented / unused code. (unnecessary noise)

2022-04-20 17:37 UTC, sezeranoJchrisostome requested changes
Well done @jeandamascyifuzo , take look on this request

2022-04-20 17:37 UTC, sezeranoJchrisostome commented on models/profile.js
> +  class Profile extends Model {
I don't think we need this model since this column is located in in users model, you delete it I guess

2022-04-21 21:37 UTC, chanceDira approved these changes
**_Well done._**

2022-04-21 21:37 UTC, chanceDira commented on function/validation.js
> +    const value = schema.validate(data , { abortEarly: false });
@jeandamascyifuzo great work on this. let keep using joi validation.

2022-04-22 07:06 UTC, sezeranoJchrisostome approved these changes

2022-04-22 07:52 UTC, Jkadhuwa approved these changes

2022-04-22 07:53 UTC, merged